"""Recompute smart scores under the calibrated anomaly penalty.

The smart-score formula changed: the binary "sum integer weights of present penalised
tags" term was replaced by a confidence- and precision-weighted, noisy-OR family penalty,
and a CLIP-IQA objective quality term was added (see
``docs/reviews/2026-06-smart-score-calibrated-anomaly-plan.md``). Existing stored
``smart_score`` values were produced by the old formula, so this migration NULL-resets the
column; ``MissingSmartScoreFinder`` then recomputes every picture under the new rule on the
next run. Schema-only otherwise - no columns are added or removed.

Revision ID: 0062_recompute_smart_score_calibrated_anomaly
Revises: 0061_add_detection
Create Date: 2026-06-20 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0062_recompute_smart_score_calibrated_anomaly"
down_revision: Union[str, None] = "0061_add_detection"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes under the calibrated-anomaly formula.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
