"""Force the cached tag-health board to recompute (est_wrong/est_missing fix).

``est_wrong``/``est_missing`` over-counted: they included pictures a human had
already adjudicated (a human-CONFIRMED tag the model doubts was counted "wrong";
a human-REJECTED tag the model still predicts high was counted "missing"). The
service now restricts both to un-reviewed rows (``label_state == "UNKNOWN"``), so
existing cached ``tag_health`` rows hold stale, over-counted values.

Unlike the ``smart_score`` finder pattern, the board is NOT refreshed by a
``Missing*Finder`` scanning for NULL columns - it is rebuilt wholesale, and its
auto-rebuild is gated on ``tag_health_service.is_stale`` (``latest_change >
computed_at``), which a pure code change never trips. NULL-resetting a column is
therefore the wrong lever here: a NULL ``computed_at`` reads as "never built"
(``max`` is NULL → ``is_stale`` False), which would suppress the auto-rebuild and
leave the stale rows on screen claiming freshness. Instead we backdate
``computed_at`` to the epoch so ``is_stale`` flips True on any non-empty vault and
``TagHealthAutoRebuildFinder`` recomputes the board within its check interval; the
(slightly stale) old rows remain visible, flagged stale, until it does. Schema-only
otherwise - no columns are added or removed.

Revision ID: 0074_recompute_tag_health_exclude_human_decisions
Revises: 0073_add_pictureset_locked
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0074_recompute_tag_health_exclude_human_decisions"
down_revision: Union[str, None] = "0073_add_pictureset_locked"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "tag_health" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("tag_health")}
    if "computed_at" not in columns:
        return
    # Backdate so is_stale flips True and the auto-rebuild finder recomputes the
    # board under the un-reviewed-only est_wrong/est_missing rule.
    op.execute(sa.text("UPDATE tag_health SET computed_at = '1970-01-01 00:00:00'"))


def downgrade() -> None:
    # No-op: tag_health is derived cache data regenerated by the rebuild path;
    # there is nothing to restore on downgrade.
    pass
