"""Recompute smart scores after the anomaly-penalty overhaul.

``Picture.smart_score`` is a cached derived column and ``MissingSmartScoreFinder`` only
picks up pictures whose score is ``NULL``, so a stored score is never recomputed on its
own. Its anomaly-penalty term is a live function of the anomaly-tag predictions, and a
series of scoring changes on this branch invalidates every stored value:

* Stale scores from tag edits made before invalidation existed. The score is now
  invalidated whenever a picture's anomaly state changes
  (``pixlstash.utils.service.smart_score_invalidation``), but scores already stale in an
  existing database cannot heal themselves.
* Graded anomaly aggregation and a soft score floor. Distinct defects accumulate with a
  rank decay and each tag contributes its own weight, and the raw score is soft-compressed
  into ``[0, 1]`` instead of hard-clipped
  (``pixlstash.utils.quality.anomaly_penalty`` / ``smart_score_utils``).
* User penalised-tag weights and the apply gate. The penalty uses the user's
  ``User.smart_score_penalised_tags`` weights, and only predictions clearing the tagger's
  per-label acceptance threshold are penalised
  (``pixlstash.picture_scoring.fetch_anomaly_confidences``).
* Threshold-relative confidence grading. A detection's confidence is normalised onto its
  tag's usable ``[threshold, 1.0]`` range before the severity exponent.

This migration NULL-resets the column once; the finder then recomputes every picture
against the current formula on the next run. Mirrors
``0062_recompute_smart_score_calibrated_anomaly``. Schema-only otherwise - no columns are
added or removed.

Revision ID: 0076_recompute_smart_score_after_stale_tag_edits
Revises: 0075_add_tag_health_ground_truth
Create Date: 2026-07-19 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0076_recompute_smart_score_after_stale_tag_edits"
down_revision: Union[str, None] = "0075_add_tag_health_ground_truth"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    columns = {c["name"] for c in inspector.get_columns("picture")}
    if "smart_score" not in columns:
        return
    # Reset so the finder recomputes against each picture's current anomaly-tag state.
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
