"""Recompute smart scores after rebalancing the positive weights.

The aesthetic and sharpness weights were reduced from 0.30 to 0.20 to de-emphasise those
two signals. Because the positive weights are summed and then compressed into ``[0, 1]``,
trimming them without redistributing also removed the headroom that makes the top of the
1-5 scale reachable: the positive total fell from 1.27 to 1.07 and, measured over 6,000
real pictures, the best achievable score became 4.38 with no picture reaching 4.5.

The 0.20 is now redistributed across the remaining positive terms (``w_good``,
``w_clipiqa``, ``w_resolution``, ``w_detail``, ``w_focus_presence``), keeping aesthetic and
sharpness de-emphasised while restoring the total to ~1.27. Every stored score was
computed under one of the two superseded weightings, so all of them are stale.

Unlike ``0083`` this reset cannot be scoped: the weights are global, so every scored
picture moves. ``MissingSmartScoreFinder`` picks the NULLed rows up on the next run.
Schema-only otherwise - no columns are added or removed.

Revision ID: 0084_recompute_smart_score_rebalanced_weights
Revises: 0083_recompute_smart_score_unapplied_anomaly_predictions
Create Date: 2026-07-26 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0084_recompute_smart_score_rebalanced_weights"
down_revision: Union[str, None] = (
    "0083_recompute_smart_score_unapplied_anomaly_predictions"
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "picture" not in inspector.get_table_names():
        return
    if "smart_score" not in {c["name"] for c in inspector.get_columns("picture")}:
        return
    op.execute(sa.text("UPDATE picture SET smart_score = NULL"))


def downgrade() -> None:
    # No-op: smart_score is derived data regenerated by the finder; there is nothing to
    # restore on downgrade.
    pass
