"""PixlStash Views - the library's sets, people and projects as folders of links.

A view folder holds one link per member picture, pointing at the file where the
owner already keeps it. Nothing is copied, no original moves, and deleting the
whole tree loses nothing: a picture in three projects appears in three view
folders and its one real file never moves. That is the answer to multi-membership
that a filesystem cannot give on its own, and it is why the tree is worth having.

**Views are additional to the owner's own tree, never a replacement for it.**

Why the location is checked before anything is written (the v1.11 spike, measured
on this machine's real filesystems - see ``docs/spikes/views-links.md``):

* Link support is a property of the **view root's** filesystem, not the library's.
  A symlink is a stored path, so it points across devices happily; measured OK
  from ext4 to a second physical drive. A library on a NAS or an external disk is
  therefore fine as long as the view root itself can hold links.
* exFAT and VFAT have **neither** symlinks nor hard links - both raise ``EPERM``,
  measured on a freshly formatted volume of each. So a hard link is not the
  fallback for the external-drive case; there is no fallback, and the answer is to
  refuse that location by name rather than write half a tree.
* A hard link never crosses a device (``EXDEV``, measured against three real
  drives), and it keeps a deleted original's bytes alive under the view folder.
  It is used only when the view root is on the same device as the file and
  symlinks are unavailable - which is the Windows-without-Developer-Mode case.
* Windows symlink creation needs ``SeCreateSymbolicLinkPrivilege`` (administrator
  or Developer Mode). Rather than predict it, :func:`probe_link_support` asks the
  filesystem by attempting one link in the chosen directory.

Refusals that are about PixlStash rather than the filesystem are in
:func:`check_views_root`. The library and reference-folder ones are measured
failures; the cloud-sync one is a precaution and says so.
"""

from __future__ import annotations

import os
import re
import stat
import threading
from dataclasses import dataclass, field
from typing import Iterable, Optional

from sqlmodel import Session, select

from pixlstash.db_models.character import Character
from pixlstash.db_models.face import Face
from pixlstash.db_models.picture import Picture
from pixlstash.db_models.picture_project import PictureProjectMember
from pixlstash.db_models.picture_set import PictureSet, PictureSetMember
from pixlstash.db_models.project import Project
from pixlstash.pixl_logging import get_logger
from pixlstash.utils.image_processing.image_utils import ImageUtils
from pixlstash.utils.path_utils import path_is_within, resolve_path_within
from pixlstash.utils.reference_folder_validator import (
    validate_reference_folder_path,
)

logger = get_logger(__name__)

SYMLINK = "symlink"
HARDLINK = "hardlink"

#: The folder name each kind publishes under, and the order they are built in.
KIND_FOLDERS = {"people": "People", "sets": "Sets", "projects": "Projects"}

#: Written at the root the first time PixlStash publishes there. Its presence is
#: the only thing that authorises deleting a subtree, so a view root aimed at a
#: folder of real pictures is refused instead of emptied.
MARKER_NAME = ".pixlstash-views"
MARKER_TEXT = (
    "This folder is generated by PixlStash. Every file in it is a link to a "
    "picture that lives elsewhere; deleting the folder deletes no picture.\n"
)

#: Directory names that mark a cloud-sync root. A sync client follows a link and
#: uploads the file's content again rather than syncing the link, so publishing
#: into one would copy the whole library into the owner's cloud quota - the exact
#: duplication views exist to avoid.
#: Deliberately NOT ``.dropbox``: the Dropbox client keeps that one in the home
#: directory, not in the synced folder, so treating it as a marker refused every
#: path under ``$HOME`` for anyone running Dropbox at all. The entries below live
#: in the synced tree itself.
_SYNC_MARKERS = {
    ".dropbox.cache",
    ".dropbox.attr",
    ".onedrive",
    ".tmp.drivedownload",
    ".tmp.driveupload",
    "com~apple~clouddocs",
}
_SYNC_DIR_NAMES = {
    "dropbox",
    "onedrive",
    "onedrive - personal",
    "google drive",
    "googledrive",
    "my drive",
    "icloud drive",
    "nextcloud",
    "pcloud drive",
    "creative cloud files",
}

#: One publish at a time. The route's handler is sync, so FastAPI runs it in a
#: threadpool and two saves can overlap - and a rebuild removes a subtree before
#: it writes it, so overlapping ones would delete each other's work and leave a
#: tree neither request asked for. Nothing outside the views root is at risk
#: either way; this is about the result being the one that was requested.
_PUBLISH_LOCK = threading.Lock()

_UNSAFE_NAME = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
_TRAILING = " ."

#: Longest entity or file name component the tree writes. See safe_component.
_MAX_COMPONENT = 80


class ViewsError(Exception):
    """A views root that must not be published to, with the reason for a human."""


@dataclass
class PublishReport:
    """What one publish actually did, so the UI can say it rather than imply it."""

    link_mode: str = SYMLINK
    folders: int = 0
    links: int = 0
    skipped_missing: int = 0
    #: View folders where at least one link could not be made - NOT folders that
    #: are absent. A folder here exists and is incomplete, which is the thing the
    #: owner has to be told, because a partial tree reads as a whole one.
    skipped_unlinkable: list[str] = field(default_factory=list)
    #: Entries the rebuild refused to delete because they were not links: the
    #: owner's own files, sitting in a view folder. They are reported rather than
    #: removed, and they are the reason the rebuild does not use ``rmtree``.
    kept_by_owner: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "link_mode": self.link_mode,
            "folders": self.folders,
            "links": self.links,
            "skipped_missing": self.skipped_missing,
            "skipped_unlinkable": self.skipped_unlinkable,
            "kept_by_owner": self.kept_by_owner,
        }


def safe_component(name: str, fallback: str) -> str:
    """Return *name* as one filesystem path component.

    Entity names are free text and routinely contain ``/``, ``:`` or a trailing
    dot, all of which are either a path separator or illegal on Windows. The
    replacement is deliberately lossy and deliberately not unique: uniqueness is
    the caller's job via :func:`_unique`, because two characters really can be
    called the same thing.

    It is also truncated, which is not cosmetic. A component over ``NAME_MAX``
    is ``ENAMETOOLONG`` on Linux, and a views path is already four segments deep
    before the name - an unremarkable set name plus a long filename clears
    Windows' 260-character ``MAX_PATH`` between them. Truncating loses a suffix;
    not truncating loses the folder.
    """
    cleaned = _UNSAFE_NAME.sub("_", (name or "").strip()).rstrip(_TRAILING).strip()
    if len(cleaned) > _MAX_COMPONENT:
        cleaned = cleaned[:_MAX_COMPONENT].rstrip(_TRAILING).strip()
    return cleaned or fallback


def _unique(taken: set[str], candidate: str, suffix: str) -> str:
    """Return *candidate*, disambiguated with *suffix* until the name is free.

    It loops rather than suffixing once, because the disambiguated form can
    itself be taken: an entity genuinely called ``0412 (7).png`` collides with
    the name picture 7 would be given, and a single pass would hand back a
    duplicate - an ``EEXIST`` at link time, reported to the owner as if the
    filesystem had refused the link.
    """
    if candidate not in taken:
        taken.add(candidate)
        return candidate
    stem, ext = os.path.splitext(candidate)
    disambiguated = f"{stem} ({suffix}){ext}"
    attempt = 2
    while disambiguated in taken:
        disambiguated = f"{stem} ({suffix}-{attempt}){ext}"
        attempt += 1
    taken.add(disambiguated)
    return disambiguated


# ---------------------------------------------------------------------------
# Where views may be published
# ---------------------------------------------------------------------------


def _sync_root_marker(directory: str) -> Optional[str]:
    """Return the cloud-sync marker found at or above *directory*, if any.

    The walk stops **below** the home directory, and that bound is the whole
    reason this check is usable. Sync clients keep configuration in ``$HOME``
    (``~/.dropbox``) and their synced tree beside it (``~/Dropbox``), so a walk
    that reached ``$HOME`` - let alone ``/`` - reported every path a Dropbox user
    could possibly pick as synced, with no override and a message asserting
    something untrue of the folder they chose. Anything at or above ``$HOME`` is
    not a sync root; something under it may be.
    """
    current = os.path.abspath(directory)
    try:
        stop = os.path.normcase(os.path.abspath(os.path.expanduser("~")))
    except (OSError, RuntimeError) as exc:
        logger.debug("Views: no home directory to bound the sync scan: %s", exc)
        stop = None
    while True:
        if stop is not None and os.path.normcase(current) == stop:
            return None
        if os.path.basename(current).lower() in _SYNC_DIR_NAMES:
            return os.path.basename(current)
        try:
            entries = {entry.lower() for entry in os.listdir(current)}
        except OSError as exc:
            logger.debug(
                "Views: could not list %s while looking for a sync marker: %s",
                current,
                exc,
            )
            entries = set()
        found = _SYNC_MARKERS & entries
        if found:
            return sorted(found)[0]
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def same_root(a: Optional[str], b: Optional[str]) -> bool:
    """Whether two host paths name the same views folder.

    A raw string comparison is not enough and the failure is silent: a file
    picker returns ``/home/me/Views`` one time and ``/home/me/Views/`` the next,
    Windows and macOS spell the same directory in several cases, and ``.``
    components survive a round trip through JSON. Any of those made the caller
    believe the folder had *changed* - so it published the new tree and then
    removed it again as "the old one", reporting success over an empty folder.
    """
    if not a or not b:
        return a == b
    return _resolved(a) == _resolved(b)


def _resolved(path: str) -> str:
    """One host path, normalised the one way this module compares them."""
    absolute = os.path.abspath(path)
    try:
        absolute = os.path.realpath(absolute)
    except OSError as exc:
        logger.debug("Views: could not resolve %s: %s", path, exc)
    return os.path.normcase(absolute)


def roots_overlap(a: Optional[str], b: Optional[str]) -> bool:
    """Whether one views root sits **strictly inside** the other.

    Publishing into a folder under the previous root - or over it - means the
    "remove the old tree" step that runs next walks the tree just written and
    deletes it, then reports success over an empty folder. It is the same
    silent shape :func:`same_root` was written for, reached by containment
    instead of by spelling, so it is refused before anything is written.

    Equal roots are deliberately not an overlap: nothing is removed in that
    case, which is exactly what :func:`same_root` is asked first.
    """
    if not a or not b:
        return False
    first, second = _resolved(a), _resolved(b)
    if first == second:
        return False
    return first.startswith(second + os.sep) or second.startswith(first + os.sep)


def check_views_root(root: str, vault, other_library_roots: Iterable[str] = ()) -> None:
    """Raise :class:`ViewsError` when *root* must not hold the views tree.

    Each refusal is a measured failure rather than a caution:

    * **Inside the library root.** ``library_backup_service`` refuses to archive
      a symlinked payload (``Refusing symlinked library payload``), so a views
      tree under ``image_root`` breaks the owner's backups outright.
    * **Inside a reference folder.** The reference-folder scan lists symlinked
      files in ``os.walk``'s ``files``, so every picture would be indexed a
      second time under its view path.
    * **Containing the library.** The same two problems, reached from the other
      side, plus a rebuild that would delete into the library.
    * **A restricted system directory**, by the shared blocklist, resolved first
      so a symlink cannot launder one past it.
    * **A cloud-sync folder.** The client follows links and uploads the content,
      which duplicates the library rather than referencing it. This one is a
      **precaution, not a measurement**: no sync client was available to test
      against, and the refusal exists so the answer never has to be known. It is
      detected by name and by the client's own marker directories, so it is the
      one refusal here that can be wrong in both directions.
    """
    if not root or not os.path.isabs(root):
        raise ViewsError("Choose a full path for the views folder.")

    # The same blocklist every other path-taking route applies, on the resolved
    # path. Without it this function's refusals were all *relative* - inside the
    # library, inside a reference folder, a sync folder - and a root that was
    # none of those was accepted anywhere on the disk, including a system
    # directory the rest of the app refuses outright. `_prepare_root` then
    # creates the folder and writes the marker into it.
    # `os.path.realpath`, not this module's `_resolved`: that one applies
    # `normcase`, which lowercases on Windows, and the blocklist entries are
    # spelled `C:\Windows`. Passing a case-folded path made the check match
    # nothing on Windows - a refusal that never fires is worse than none,
    # because the coverage matrix records it as present.
    blocked = validate_reference_folder_path(os.path.realpath(os.path.abspath(root)))
    if blocked:
        raise ViewsError(blocked)

    image_root = getattr(vault, "image_root", None)
    if image_root:
        if path_is_within(root, image_root):
            raise ViewsError(
                "That folder is inside the library. Backups refuse a library "
                "containing links, so choose a folder outside it."
            )
        if path_is_within(image_root, root):
            raise ViewsError(
                "That folder contains the library itself. Choose one beside it "
                "rather than above it."
            )

    for reference_root in getattr(vault, "reference_folder_roots", lambda: ())():
        if path_is_within(root, reference_root):
            raise ViewsError(
                "That folder is inside a reference folder, so the next scan "
                "would index every link as a second copy of the picture."
            )
        if path_is_within(reference_root, root):
            raise ViewsError(
                "That folder contains a reference folder. Choose one beside "
                "your pictures rather than above them."
            )

    for library_root in other_library_roots:
        if path_is_within(root, library_root) or path_is_within(library_root, root):
            raise ViewsError(
                "That folder overlaps another library you have registered. "
                "Backups refuse a library containing links, so choose a folder "
                "outside every library."
            )

    marker = _sync_root_marker(root)
    if marker:
        raise ViewsError(
            f"That folder is synced by a cloud client ({marker}). Sync clients "
            "upload the file a link points at instead of the link, which would "
            "copy your whole library into the cloud. Choose a local folder."
        )


def probe_link_support(directory: str, target_file: str) -> tuple[Optional[str], str]:
    """Ask *directory*'s filesystem whether it can link to *target_file*.

    Attempts one symlink and then one hard link, removing whatever it made. The
    answer is measured rather than predicted because it depends on the
    filesystem (exFAT and VFAT refuse both), on whether the two paths share a
    device (a hard link cannot cross one) and, on Windows, on whether this
    process holds ``SeCreateSymbolicLinkPrivilege`` - which administrator rights
    or Developer Mode grant and nothing in the file's metadata reveals.

    Returns:
        ``(mode, reason)`` where *mode* is :data:`SYMLINK`, :data:`HARDLINK` or
        ``None``, and *reason* explains a ``None`` to the owner.
    """
    probe = os.path.join(directory, ".pixlstash-views-probe")
    for mode, make in ((SYMLINK, os.symlink), (HARDLINK, os.link)):
        try:
            make(target_file, probe)
        except OSError as exc:
            logger.info(
                "Views: %s links are unavailable in %s (target %s): %s",
                mode,
                directory,
                target_file,
                exc,
            )
            continue
        finally:
            if os.path.lexists(probe):
                try:
                    os.remove(probe)
                except OSError as exc:
                    logger.warning(
                        "Views: could not remove the link probe %s: %s", probe, exc
                    )
        return mode, ""
    return None, (
        "This folder cannot hold links. exFAT and FAT drives have neither kind, "
        "and on Windows symbolic links need administrator rights or Developer "
        "Mode. Choose a folder on an internal drive."
    )


# ---------------------------------------------------------------------------
# Reading the library
# ---------------------------------------------------------------------------


def collect_in_session(
    session: Session, kinds: Iterable[str]
) -> dict[str, list[tuple]]:
    """Return ``{kind: [(entity_id, name, [picture rows])]}`` for *kinds*.

    Takes a session rather than a vault (§10.1): the caller owns the queued read,
    so :func:`publish` is pure filesystem work over data it is handed.
    """
    wanted = set(kinds)
    collected: dict[str, list[tuple]] = {}

    if "people" in wanted:
        rows = session.exec(
            select(Character.id, Character.name, Picture)
            .join(Face, Face.character_id == Character.id)
            .join(Picture, Picture.id == Face.picture_id)
            .where(Picture.deleted == False)  # noqa: E712 - SQL, not Python truthiness
        ).all()
        collected["people"] = _group(rows)

    if "sets" in wanted:
        rows = session.exec(
            select(PictureSet.id, PictureSet.name, Picture)
            .join(PictureSetMember, PictureSetMember.set_id == PictureSet.id)
            .join(Picture, Picture.id == PictureSetMember.picture_id)
            .where(Picture.deleted == False)  # noqa: E712
        ).all()
        collected["sets"] = _group(rows)

    if "projects" in wanted:
        rows = session.exec(
            select(Project.id, Project.name, Picture)
            .join(PictureProjectMember, PictureProjectMember.project_id == Project.id)
            .join(Picture, Picture.id == PictureProjectMember.picture_id)
            .where(Picture.deleted == False)  # noqa: E712
        ).all()
        collected["projects"] = _group(rows)

    return collected


def _group(rows) -> list[tuple]:
    """Fold ``(id, name, picture)`` rows into one entry per entity.

    A picture with two faces of the same character appears twice in the join, so
    membership is deduplicated by picture id here rather than in SQL - the query
    stays one readable join and the set is small.
    """
    grouped: dict[int, tuple[str, dict[int, Picture]]] = {}
    for entity_id, name, picture in rows:
        entry = grouped.setdefault(entity_id, (name, {}))
        entry[1][picture.id] = picture
    return [
        (entity_id, name, list(pictures.values()))
        for entity_id, (name, pictures) in grouped.items()
    ]


# ---------------------------------------------------------------------------
# Publishing
# ---------------------------------------------------------------------------


def _prepare_root(root: str) -> None:
    """Create *root* and claim it, refusing a folder that already holds content.

    The marker is what authorises the rebuild's deletes. Without it a views root
    aimed at a folder of real pictures would be emptied on the next publish, so a
    non-empty unclaimed folder is refused rather than adopted.
    """
    if os.path.exists(root):
        if not os.path.isdir(root):
            raise ViewsError("That path is a file, not a folder.")
        marker = os.path.join(root, MARKER_NAME)
        if not os.path.exists(marker):
            try:
                occupied = bool(os.listdir(root))
            except OSError as exc:
                # Unreadable is not empty. Refusing is the only safe reading,
                # because the alternative is deleting inside a folder whose
                # contents could not be checked.
                raise ViewsError(f"Could not read that folder: {exc}") from exc
            if occupied:
                raise ViewsError(
                    "That folder already has things in it. Choose an empty "
                    "folder, or one PixlStash published views to before."
                )
    else:
        try:
            os.makedirs(root, exist_ok=True)
        except OSError as exc:
            raise ViewsError(f"Could not create that folder: {exc}") from exc
    try:
        with open(os.path.join(root, MARKER_NAME), "w", encoding="utf-8") as handle:
            handle.write(MARKER_TEXT)
    except OSError as exc:
        raise ViewsError(f"Could not write to that folder: {exc}") from exc


def _prune(directory: str) -> list[str]:
    """Remove every link under *directory*, and nothing that is the only copy.

    **This is the rule that stands between a rebuild and someone's pictures.**
    ``shutil.rmtree`` is not link-aware: it deletes a regular file as happily as
    a symlink, so a rebuild that used it would destroy anything the owner had
    dropped into a view folder - and every line of this feature's copy invites
    them to treat these folders as ordinary ones. So the deletes are decided per
    entry, and the test is exact rather than heuristic:

    * a **symlink** is removed - it is a path, and unlinking it loses nothing;
    * a regular file with ``st_nlink > 1`` is removed - another name for those
      bytes exists elsewhere, which is exactly what a hard link into the library
      is, so unlinking this one loses nothing;
    * **anything else stays**, and is named to the caller. A regular file whose
      only name is here is the owner's, however it arrived.

    A directory that still holds something afterwards is kept. Nothing here
    follows a symlinked directory: those are removed as links, not descended
    into, which is also what stops a symlink planted in the views root from
    steering the rebuild outside it.

    Returns:
        The paths that were kept, relative to *directory*, so the caller can say
        which folders it did not fully own.
    """
    kept: list[str] = []
    if not os.path.isdir(directory) or os.path.islink(directory):
        return kept
    for parent, dirs, files in os.walk(directory, topdown=False, followlinks=False):
        for name in files + dirs:
            path = os.path.join(parent, name)
            try:
                info = os.lstat(path)
                if stat.S_ISLNK(info.st_mode):
                    os.remove(path)
                    continue
                if stat.S_ISDIR(info.st_mode):
                    os.rmdir(path)  # bottom-up, so this succeeds iff it emptied
                    continue
                if stat.S_ISREG(info.st_mode) and info.st_nlink > 1:
                    os.remove(path)
                    continue
            except OSError as exc:
                logger.info("Views: keeping %s, which did not come away: %s", path, exc)
                if not os.path.lexists(path):
                    # It went away between the walk and the unlink - a viewer
                    # tidying up, another process, the owner. Nothing is kept,
                    # and re-``lstat``ing to find that out would raise inside
                    # this handler and abort the whole publish.
                    continue
                if name in dirs:
                    # A directory only survives because something inside it did.
                    # That thing is already named; naming its parent as well
                    # would report one kept file as two.
                    continue
            kept.append(os.path.relpath(path, directory))
    return kept


def _prune_all(root: str) -> list[str]:
    """Prune every kind folder under *root*, and report what would not come away."""
    kept: list[str] = []
    for folder in KIND_FOLDERS.values():
        kind_dir = os.path.join(root, folder)
        if os.path.islink(kind_dir):
            # A symlink standing where a kind folder goes would send the whole
            # rebuild through it and out of the views root. Remove the link
            # itself; whatever it pointed at is not ours to touch.
            try:
                os.remove(kind_dir)
            except OSError as exc:
                logger.warning("Views: could not remove the link %s: %s", kind_dir, exc)
                kept.append(folder)
            continue
        this_kind = _prune(kind_dir)
        kept.extend(f"{folder}/{entry}" for entry in this_kind)
        if os.path.isdir(kind_dir) and not this_kind:
            try:
                os.rmdir(kind_dir)
            except OSError as exc:
                logger.debug("Views: %s is not empty after pruning: %s", kind_dir, exc)
    return kept


def _link_target(mode: str, source: str, view_dir: str) -> str:
    """Return the value to link *source* as from inside *view_dir*.

    A symlink is stored relative when both sides share a device, so moving the
    library and its views together keeps every link valid; across devices a
    relative path is either impossible (different drive letters on Windows) or
    absurd, so the absolute path is stored. A hard link takes the real path
    either way - it is an inode reference, not a path.
    """
    if mode != SYMLINK:
        return source
    try:
        if os.stat(os.path.dirname(source)).st_dev == os.stat(view_dir).st_dev:
            return os.path.relpath(source, view_dir)
    except (OSError, ValueError) as exc:
        # ValueError is the Windows case: os.path.relpath refuses two drive
        # letters outright. st_dev already separates those, so this is the belt
        # for a filesystem whose device ids agree across a boundary relpath
        # still will not cross.
        logger.debug("Views: falling back to an absolute link for %s: %s", source, exc)
    return source


def publish(
    vault,
    root: str,
    kinds: Iterable[str],
    collected: dict[str, list[tuple]],
    other_library_roots: Iterable[str] = (),
) -> PublishReport:
    """Rebuild the views tree at *root* from the library, and report what landed.

    The rebuild is a full re-derive: each published kind's folder is removed and
    written again. That costs a fraction of a second even for a large library
    (50,000 symlinks measured at 0.46 s to create and 0.34 s to remove), so there
    is no incremental path to get wrong, and a tree of links is disposable by
    construction.
    """
    with _PUBLISH_LOCK:
        return _publish_locked(vault, root, kinds, collected, other_library_roots)


def _publish_locked(
    vault, root, kinds, collected, other_library_roots=()
) -> PublishReport:
    kinds = [kind for kind in KIND_FOLDERS if kind in set(kinds)]
    check_views_root(root, vault, other_library_roots)
    _prepare_root(root)
    report = PublishReport()

    sample = next(
        (
            resolved
            for entries in collected.values()
            for _, _, pictures in entries
            for resolved in (
                ImageUtils.resolve_picture_path(vault.image_root, p.file_path)
                for p in pictures
            )
            if resolved and os.path.isfile(resolved)
        ),
        None,
    )
    if sample is not None:
        # Probed BEFORE anything is removed, so a folder that turns out not to
        # hold links does not cost the owner the tree they already had.
        mode, reason = probe_link_support(root, sample)
        if mode is None:
            raise ViewsError(reason)
        report.link_mode = mode

    # EVERY kind folder is pruned, not only the requested ones. Publishing
    # ``people`` alone after publishing ``people,sets`` must not leave ``Sets/``
    # behind full of links nothing will ever refresh: a kind that is switched off
    # is a kind whose folder should not exist. This is also what makes an empty
    # ``kinds`` mean an empty tree, which is what the API says it means.
    report.kept_by_owner = _prune_all(root)

    if sample is None:
        # Nothing to link, and the tree has just been emptied, which is the
        # honest answer when the last member of every view was removed.
        return report

    for kind in kinds:
        kind_dir = resolve_path_within(root, KIND_FOLDERS[kind])
        try:
            os.makedirs(kind_dir, exist_ok=True)
        except OSError as exc:
            logger.info("Views: could not create %s: %s", kind_dir, exc)
            report.skipped_unlinkable.append(KIND_FOLDERS[kind])
            continue
        taken_folders: set[str] = set()
        for entity_id, name, pictures in collected[kind]:
            folder = _unique(
                taken_folders,
                safe_component(name, f"{KIND_FOLDERS[kind]} {entity_id}"),
                str(entity_id),
            )
            view_dir = resolve_path_within(kind_dir, folder)
            try:
                os.makedirs(view_dir, exist_ok=True)
            except OSError as exc:
                # One folder PixlStash cannot create - a Windows reserved name
                # like ``CON``, a path over the length limit, a permission - is
                # that folder's problem. Naming it beats a 500 that loses the
                # whole tree, and beats a tree that quietly lacks it.
                logger.info("Views: could not create %s: %s", view_dir, exc)
                report.skipped_unlinkable.append(f"{KIND_FOLDERS[kind]}/{folder}")
                continue
            report.folders += 1
            taken_files: set[str] = set()
            for picture in pictures:
                source = ImageUtils.resolve_picture_path(
                    vault.image_root, picture.file_path
                )
                if not source or not os.path.isfile(source):
                    report.skipped_missing += 1
                    continue
                link_name = _unique(
                    taken_files,
                    safe_component(os.path.basename(source), f"{picture.id}"),
                    str(picture.id),
                )
                link_path = resolve_path_within(view_dir, link_name)
                target = _link_target(mode, source, view_dir)
                try:
                    if mode == SYMLINK:
                        os.symlink(target, link_path)
                    else:
                        os.link(target, link_path)
                except OSError as exc:
                    # A hard link that cannot reach this file's drive is the
                    # expected case for a library spanning two disks. Name it
                    # rather than failing the whole publish.
                    logger.info(
                        "Views: could not link %s into %s (%s mode): %s",
                        source,
                        view_dir,
                        mode,
                        exc,
                    )
                    entry = f"{KIND_FOLDERS[kind]}/{folder}"
                    if entry not in report.skipped_unlinkable:
                        report.skipped_unlinkable.append(entry)
                    continue
                report.links += 1

    logger.info(
        "Views: published %d links in %d folders at %s using %s links "
        "(%d files missing, %d folders partly unlinkable)",
        report.links,
        report.folders,
        root,
        report.link_mode,
        report.skipped_missing,
        len(report.skipped_unlinkable),
    )
    return report


def remove(root: str) -> None:
    """Remove a published views tree, leaving a folder PixlStash did not create.

    Only the kind folders and the marker go. The root itself stays because the
    owner chose it and may have made it for this; deleting it would be tidier and
    would be the one destructive surprise this feature could still produce.
    """
    with _PUBLISH_LOCK:
        _remove_locked(root)


def _remove_locked(root: str) -> None:
    if not root or not os.path.isdir(root):
        return
    if not os.path.exists(os.path.join(root, MARKER_NAME)):
        logger.warning(
            "Views: refusing to clear %s because it carries no %s marker.",
            root,
            MARKER_NAME,
        )
        return
    kept = _prune_all(root)
    if kept:
        # The marker stays while anything is still standing in the tree. It is
        # what tells the reference-folder scan to leave these files alone, and
        # dropping it over a partial removal would hand every surviving link to
        # the next scan as a new picture.
        logger.warning(
            "Views: %s still holds %d entries PixlStash did not put there, so "
            "the tree and its marker are left in place: %s",
            root,
            len(kept),
            ", ".join(kept[:10]),
        )
        return
    try:
        os.remove(os.path.join(root, MARKER_NAME))
    except OSError as exc:
        logger.warning("Views: could not remove the marker in %s: %s", root, exc)
