"""One-off script: strip regenerable data from existing snapshot files.

Walks every ``.sqlite`` snapshot file under ``<image_root>/snapshots/`` and:

  1. NULLs the regenerable Picture columns
     (``text_embedding``, ``image_embedding``, ``smart_score``,
     ``text_score``, ``aesthetic_score``);
  2. deletes every row from the likeness-pipeline tables
     (``picturelikeness``, ``picturelikenessqueue``,
     ``picturelikenessfrontier``);

then runs ``VACUUM`` to reclaim the freed pages.

These values are all regenerated by the WorkPlanner / likeness pipeline
after a restore - and the full-restore path captures + replays the LIVE
likeness queue + frontier across the file swap, so the snapshot's own
copies are pure waste. On a vault dominated by CLIP embeddings and a
saturated likeness graph this can reclaim 90%+ of the snapshot file.

The script is **safe to re-run** - already-stripped snapshots become
no-op UPDATEs and DELETEs. Snapshot manifests are not touched.

Usage:
    python scripts/strip_snapshot_blobs.py <image_root> [--dry-run]

Examples:
    python scripts/strip_snapshot_blobs.py ~/.config/pixlstash/images
    python scripts/strip_snapshot_blobs.py /vault --dry-run
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys


_PICTURE_COLUMNS_TO_NULL: tuple[str, ...] = (
    "text_embedding",
    "image_embedding",
    "smart_score",
    "text_score",
    "aesthetic_score",
)

# Regenerable / pipeline-state tables whose entire contents are dropped.
# The likeness-graph tables are typically the dominant disk consumer on
# a large vault - likeness is O(N²) up to the per-picture top-K cap.
_TABLES_TO_DELETE: tuple[str, ...] = (
    "picturelikeness",
    "picturelikenessqueue",
    "picturelikenessfrontier",
)


def _strip_one(snap_path: str, *, dry_run: bool) -> tuple[int, int]:
    """Strip a single snapshot file. Returns (size_before, size_after)."""
    size_before = os.path.getsize(snap_path)
    if dry_run:
        return size_before, size_before

    conn = sqlite3.connect(snap_path)
    try:
        cols_present = {
            row[1] for row in conn.execute("PRAGMA table_info(picture)").fetchall()
        }
        if not cols_present:
            # Not a vault snapshot (no ``picture`` table); skip.
            return size_before, size_before
        null_cols = [c for c in _PICTURE_COLUMNS_TO_NULL if c in cols_present]
        if null_cols:
            set_clause = ", ".join(f"{c} = NULL" for c in null_cols)
            conn.execute(f"UPDATE picture SET {set_clause}")

        existing_tables = {
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        }
        for table_name in _TABLES_TO_DELETE:
            if table_name in existing_tables:
                conn.execute(f"DELETE FROM {table_name}")

        conn.commit()
        conn.isolation_level = None
        conn.execute("VACUUM")
    finally:
        conn.close()

    return size_before, os.path.getsize(snap_path)


def _human_bytes(n: int) -> str:
    units = ["B", "KB", "MB", "GB", "TB"]
    f = float(n)
    for u in units:
        if f < 1024 or u == units[-1]:
            return f"{f:.1f} {u}"
        f /= 1024
    return f"{n} B"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Strip regenerable Picture BLOB columns from every snapshot "
            "under <image_root>/snapshots/ and re-VACUUM to reclaim disk."
        )
    )
    parser.add_argument(
        "image_root",
        help="Path to the vault image root directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report current size of each snapshot; do not modify files.",
    )
    args = parser.parse_args()

    image_root = os.path.abspath(args.image_root)
    if not os.path.isdir(image_root):
        print(f"Error: image_root does not exist: {image_root}", file=sys.stderr)
        sys.exit(1)

    snapshots_dir = os.path.join(image_root, "snapshots")
    if not os.path.isdir(snapshots_dir):
        print(
            f"Error: no snapshots directory at {snapshots_dir}; nothing to do.",
            file=sys.stderr,
        )
        sys.exit(1)

    snap_files: list[str] = []
    for root, _dirs, files in os.walk(snapshots_dir):
        for name in files:
            if name.endswith(".sqlite"):
                snap_files.append(os.path.join(root, name))

    if not snap_files:
        print("No .sqlite snapshot files found; nothing to do.")
        return

    print(
        f"Found {len(snap_files)} snapshot file(s) under {snapshots_dir} "
        f"({'dry-run' if args.dry_run else 'will strip and VACUUM'})."
    )

    total_before = 0
    total_after = 0
    for path in sorted(snap_files):
        try:
            before, after = _strip_one(path, dry_run=args.dry_run)
        except Exception as exc:
            print(
                f"  ! {path}: skipped (error: {exc})",
                file=sys.stderr,
            )
            continue
        total_before += before
        total_after += after
        rel = os.path.relpath(path, image_root)
        if args.dry_run:
            print(f"  {rel}: {_human_bytes(before)}")
        else:
            reclaimed = before - after
            pct = (100.0 * reclaimed / before) if before else 0.0
            print(
                f"  {rel}: {_human_bytes(before)} → {_human_bytes(after)} "
                f"(reclaimed {_human_bytes(reclaimed)}, {pct:.0f}%)"
            )

    if args.dry_run:
        print(f"\nTotal current size: {_human_bytes(total_before)}")
        print("Re-run without --dry-run to strip.")
    else:
        reclaimed = total_before - total_after
        pct = (100.0 * reclaimed / total_before) if total_before else 0.0
        print(
            f"\nDone. {_human_bytes(total_before)} → {_human_bytes(total_after)} "
            f"(reclaimed {_human_bytes(reclaimed)}, {pct:.0f}%)"
        )


if __name__ == "__main__":
    main()
